### ISSUE TITLE
Hiding unsafety.

### ISSUE THREAD

**Issue by dpc** [sfackler/foreign-types#10]
So, I was looking into a `crev` review of this crate: https://github.com/MaulingMonkey/crev-proofs/commit/3a450f6b2aadf2d8fdffb9e0133ebd9563791705 and I kind of agree with the conclusion there. It seems that using `foreign_type!` allows skipping the `unsafe` keyword and potentially obscuring to the reviewer that the underlying code contains `unsafe`.

Since this is a macro and not a function, it remains a bit of a gray area, I guess. But I just wanted to bring it up.

Maybe the macro should always be invoked like:

```
unsafe {
  foreign_type! {
     ...
  }
}
```

or alternatively, maybe it should be at least named `unsafe_foreign_type!`.

**Comment by sfackler** [comment]
That's not valid syntax, but other options that should work are

```rust
foreign_type! {
    pub unsafe type Foo: Send {
        type CType = foo_sys::FOO;
        fn drop = foo_sys::foo_free;
    };
}
```

or

```rust
foreign_type! {
    pub type Foo: unsafe Send {
        type CType = foo_sys::FOO;
        unsafe fn drop = foo_sys::foo_free;
    };
}
```

**Comment by dpc** [comment]
I confirmed with the original reporter and we're both happy. Thanks!
