### ISSUE TITLE
Use of uninhabited enums

### ISSUE THREAD

**Issue by madsmtm** [sfackler/foreign-types#15]
This library suggests using uninhabited enums to represent opaque types. From the first example:
```rust
mod foo_sys {
    pub enum FOO {}

    extern {
        pub fn FOO_free(foo: *mut FOO);
    }
}
```

I'm not entirely sure, but I think using uninhabited enums are here is undefined behaviour (though it currently emits the same LLVM IR), see [this entry](https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs) in The Rustonomicon. The recommended approach should be zero sized `#[repr(C)]` structs (or `extern type`s when they stabilize).

**Comment by sfackler** [comment]
The specific concern in that page is accidentally creating references to uninhabited types, not raw pointers.
