### ISSUE TITLE
Consider changing back to `macro_rules!`?

### ISSUE THREAD

**Issue by madsmtm** [sfackler/foreign-types#21]
In c99fda385527419a4a3a539da6c52e5326999bbc the `foreign_type!` macro was switched from a `macro_rules!` macro/"macro by example" to a procedural macro. This allows more advanced things like creating new identifiers (user specifies `Foo`, macro creates `FooRef`).

However, there are a few downsides to using a procedural macro, in my eyes the most important one being compile times (but I personally also find proc macro code harder to read, and tools like `rust-analyzer` have a harder time with it) - as an example, @avitex' [update of `foreign-types` in `core-foundation-rs`](https://github.com/avitex/core-foundation-rs/tree/update-foreign-types) makes the build go from ~20s to ~30s on my machine, because of the added proc macro dependencies and compilation.

Would you consider going back to using `macro_rules!`? I would probably be willing to implement this, the biggest hurdle is probably that the syntax would have to be changed again so that the `FooRef` identifier is specified by the user. A few ideas:
```rust
// Current
foreign_type! {
    /// Foo doc
    pub unsafe type Foo: Sync + Send // optional
    {
        type CType = foo_sys::FOO;
        fn drop = foo_sys::FOO_free;
        fn clone = foo_sys::FOO_duplicate; // optional
    }
}

// Idea #1
foreign_type! {
    /// Foo doc
    pub unsafe type Foo: Sync + Send // optional
    {
        type CType = foo_sys::FOO;
        /// FooRef doc
        pub type RefType = FooRef;
        fn drop = foo_sys::FOO_free;
        fn clone = foo_sys::FOO_duplicate; // optional
    }
}

// Idea #2
foreign_type! {
    /// Foo doc
    pub unsafe type Foo: Sync + Send // optional
    {
        /// FooRef doc
        pub type FooRef = foo_sys::FOO;
        fn drop = foo_sys::FOO_free;
        fn clone = foo_sys::FOO_duplicate; // optional
    }
}

// Idea #3
foreign_type! {
    /// Foo doc
    pub unsafe type Foo: Sync + Send // optional
    {
        /// FooRef doc
        pub ref type FooRef; // Possibly also with Sync and Send here?
        type CType = foo_sys::FOO;
        fn drop = foo_sys::FOO_free;
        fn clone = foo_sys::FOO_duplicate; // optional
    }
}
```

**Comment by sfackler** [comment]
I don't want to require FooRef to be named manually. You could try using https://docs.rs/paste/latest/paste/ to construct the name.

However, this should only increase build times if you don't have any other dependencies that pull in `syn`. Given the wide use of things like Serde, how common is that actually?

**Comment by madsmtm** [comment]
I don't know how common it is to not have dependencies on `syn` - but if you don't want `FooRef` to be named manually, then I guess the point is a bit moot anyhow (since, as you said, we'd require using the `paste` library, and I think my desire was to have as small a dependency tree as possible).

Thanks for the response though!
