### ISSUE TITLE
Provide example of providing a lifetime parameter

### ISSUE THREAD

**Issue by metasim** [sfackler/foreign-types#23]
I tried to use the generics support in `foreign_types` like this:

```
foreign_type! {
    pub unsafe type Feature<'a> {
        type CType = libc::c_void;
        type PhantomData = 'a;
        fn drop = feature_dtor;
    }
}
```

The compiler error I get is:

```
error: at least one trait is required for an object type
  --> src/foo/bar.rs:21:28
   |
21 |         type PhantomData = 'a;
   |                            ^^
```

Is there some other way of doing this using the macro? Or maybe I'm using it incorrectly?

**Comment by sfackler** [comment]
`'a` is a lifetime, not a type. See here for example of using `&'a ()`: https://docs.rs/foreign-types/latest/foreign_types/macro.foreign_type.html#examples

**Comment by metasim** [comment]
@sfackler Perfect! Apologies for missing that example. Much appreciated.
